name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.3.0
  common:
    path: ../common
  hasura_connect: ^4.0.0+4
  shelf: ^1.4.0
  shelf_modular: ^2.1.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
